name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Regenerate docs
        run: |
            rm -rf docs
            ./gradlew dokkaHtml
            mv app/build/dokka/html ./docs
      - name: Push docs
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "Actions Bot"
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "[Auto] update docs"
          git push -u origin master
          
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: docs
  
